### ISSUE TITLE
Can't seem to connect to Archipelago server

### ISSUE THREAD

**Issue by lioncash** [Dinopony/randstalker-archipelago#1]
Hi, 

I'm trying to connect to a game, and so far all that happens is that it spins waiting trying to connect to the server forever (even when run as administrator, and explicitly allowed through the firewall, host url double checked, etc) and I can't really provide more info than that because nothing new ever gets printed to the output console and it seems like the timeout duration is extremely long:

![image](https://github.com/Dinopony/randstalker-archipelago/assets/712067/76626c9b-be09-400d-ab8e-517b55705755)

I know the server host URL and port work and they're not inactive, because I'm able to connect (e.g. via bizhawk, etc) for other games that are part of the async.

Is there anything obvious that would prevent this from working that I might be missing?

**Comment by Dinopony** [comment]
I believe main website rooms now use the secure WSS protocol instead of WS.
What happens if you put `wss://archipelago.gg:64845` as host instead?
This is a user-friendliness issue that will get fixed soon 😉

**Comment by lioncash** [comment]
Ahh, ok that was it. Thanks!
